require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/my_searches", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MySearch. As you add validations to MySearch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MySearch.create! valid_attributes
      get my_searches_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      my_search = MySearch.create! valid_attributes
      get my_search_url(my_search)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_my_search_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      my_search = MySearch.create! valid_attributes
      get edit_my_search_url(my_search)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MySearch" do
        expect {
          post my_searches_url, params: { my_search: valid_attributes }
        }.to change(MySearch, :count).by(1)
      end

      it "redirects to the created my_search" do
        post my_searches_url, params: { my_search: valid_attributes }
        expect(response).to redirect_to(my_search_url(MySearch.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MySearch" do
        expect {
          post my_searches_url, params: { my_search: invalid_attributes }
        }.to change(MySearch, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post my_searches_url, params: { my_search: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested my_search" do
        my_search = MySearch.create! valid_attributes
        patch my_search_url(my_search), params: { my_search: new_attributes }
        my_search.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the my_search" do
        my_search = MySearch.create! valid_attributes
        patch my_search_url(my_search), params: { my_search: new_attributes }
        my_search.reload
        expect(response).to redirect_to(my_search_url(my_search))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        my_search = MySearch.create! valid_attributes
        patch my_search_url(my_search), params: { my_search: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested my_search" do
      my_search = MySearch.create! valid_attributes
      expect {
        delete my_search_url(my_search)
      }.to change(MySearch, :count).by(-1)
    end

    it "redirects to the my_searches list" do
      my_search = MySearch.create! valid_attributes
      delete my_search_url(my_search)
      expect(response).to redirect_to(my_searches_url)
    end
  end
end
